name: nginx
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config:/etc/nginx/conf.d
      - /opt/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/acs/biblioplexo:/var/www/biblioplexo
    networks:
      - proxy
      - validata_app-network

networks:
  proxy:
    external: true
  validata_app-network:
    external: true
